=== DlRTY-HARRY/openmdx/core/src/resource/org/openmdx/kernel/application/deploy/openmdx-application-client_1_1.dtd
<!--
 ! ====================================================================
 ! Project:     openmdx, http://www.openmdx.org/
 ! Name:        $Id: openmdx-application-client_1_1.dtd,v 1.4 2005/01/12 19:20:16 hburger Exp $
 ! Description: openMDX J2EE Application Client Extension 1.0
 ! Revision:    $Revision: 1.4 $
 ! Owner:       OMEX AG, Switzerland, http://www.omex.ch
 ! Date:        $Date: 2005/01/12 19:20:16 $
 ! ====================================================================
 !
 ! This software is published under the BSD license
 ! as listed below.
 ! 
 ! Copyright (c) 2004, OMEX AG, Switzerland
 ! All rights reserved.
 ! 
 ! Redistribution and use in source and binary forms, with or
 ! without modification, are permitted provided that the following
 ! conditions are met:
 ! 
 ! * Redistributions of source code must retain the above copyright
 !   notice, this list of conditions and the following disclaimer.
 ! 
 ! * Redistributions in binary form must reproduce the above copyright
 !   notice, this list of conditions and the following disclaimer in
 !   the documentation and/or other materials provided with the
 !   distribution.
 ! 
 ! * Neither the name of the openMDX team nor the names of its
 !   contributors may be used to endorse or promote products derived
 !   from this software without specific prior written permission.
 ! 
 ! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 ! CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 ! INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ! MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 ! DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 ! BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 ! EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ! TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 ! DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 ! ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 ! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 ! OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 ! POSSIBILITY OF SUCH DAMAGE.
 ! 
 ! _________________
 ! 
 ! This product includes software developed by the Apache Software
 ! Foundation (http://www.apache.org/).
 !-->
<!--
XML DTD for openMDX specific J2EE Application Client Extension deployment
descriptor. This DTD is intended to be accompanied with a J2EE 
Application Client 1.3 deployment descriptor (application-client.xml).

All openMDX J2EE Application Client Extension 1.0 deployment descriptors 
must include a DOCTYPE of the following form:

  <!DOCTYPE openmdx-application-client PUBLIC 
    "-//openMDX//DTD J2EE Application Client Extension 1.1//EN" 
    "http://www.openmdx.org/dtd/openmdx-application-client_1_1.dtd">  
   
-->

<!--
The openmdx-application-client element is the root element of the openMDX 
Application Client deployment descriptor. 

It contains
	- an optional description of the openmdx-application-client file
	- an optinal login configuration name
	- an optional declaration of the bean's EJB references.
	- an optional declaration of the bean's resource references.
	
Example:

	<openmdx-application-client>
		<ejb-ref>
			<ejb-ref-name>ejb/gateway</ejb-ref-name>
			<jndi-name>org/openmdx/test/gateway</jndi-name>
		</ejb-ref>
	</openmdx-application-client>	
		
-->
<!ELEMENT openmdx-application-client (
	description?, 
	jndi-name,
	ejb-ref*, 
	resource-env-ref*,	
	resource-ref*
)>

<!--
The description element is used to provide text describing the parent element.

This is an optional element.

Used in: openmdx-application-client
-->
<!ELEMENT description (#PCDATA)>

<!-- 
This specifies a JNDI name to reference a bean
Used in: ejb-ref, resource-ref, resource-env-ref
-->
<!ELEMENT jndi-name (#PCDATA)>

<!--
The ejb-ref-name element specifies the name of an environment 
reference. Its value is the reference name used in the 
application client's deployment descriptor.
Used in: ejb-ref

Example: 
<ejb-ref-name>ejb/PetStore</ejb-ref-name>
-->
<!ELEMENT ejb-ref-name (#PCDATA)>

<!--
The res-ref-name element specifies the name of an environment 
reference. Its value is the reference name used in the 
application client's deployment descriptor.
Used in: res-ref
-->
<!ELEMENT res-ref-name (#PCDATA)>

<!--
The res-env-ref-name element specifies the name of an environment 
reference. Its value is the reference name used in the 
application client's deployment descriptor.
Used in: res-env-ref
-->
<!ELEMENT res-env-ref-name (#PCDATA)>

<!--
The ejb-ref element is used to map the ejb-ref-name of an EJB reference
(provided in application-client.xml) to a JNDI name.
Used in: openmdx-application-client
-->
<!ELEMENT ejb-ref (
	ejb-ref-name, 
	jndi-name
)>

<!--
The resource-ref element is used to map the res-ref-name of a resource 
reference (provided in application-client.xml) to a JNDI name.
Used in: openmdx-application-client
-->
<!ELEMENT resource-ref (
	res-ref-name, 
	jndi-name
)>

<!--
The resource-env-ref element is used to map the res-env-ref-name of a resource 
reference (provided in application-client.xml) to a JNDI name.
Used in: openmdx-application-client
-->
<!ELEMENT resource-env-ref (
	res-env-ref-name, 
	jndi-name
)>

=== DlRTY-HARRY/openmdx/test-ejb/src/ear/test1.ear.fully-exploded/client.jar/META-INF/openmdx-application-client.xml
<!DOCTYPE openmdx-application-client PUBLIC 
  "-//openMDX//DTD J2EE Application Client Extension 1.1//EN" 
  "http://www.openmdx.org/dtd/openmdx-application-client_1_1.dtd">     
<openmdx-application-client>
  <jndi-name>org/openmdx/test/Client</jndi-name>
  <ejb-ref>
    <ejb-ref-name>ejb/Roger</ejb-ref-name>
    <jndi-name>org/openmdx/test/Roger</jndi-name>
  </ejb-ref>
  <resource-ref>
    <res-ref-name>resource/foo</res-ref-name>
    <jndi-name>org/openmdx/test/foo</jndi-name>
  </resource-ref>
  <resource-ref>
    <res-ref-name>resource/bar</res-ref-name>
    <jndi-name>org/openmdx/test/bar</jndi-name>
  </resource-ref>
</openmdx-application-client>
