=== DlRTY-HARRY/openmdx/core/src/resource/org/openmdx/kernel/application/deploy/openmdx-ejb-jar_1_0.dtd
<!--
 ! ====================================================================
 ! Project:     openmdx, http://www.openmdx.org/
 ! Name:        $Id: openmdx-ejb-jar_1_0.dtd,v 1.12 2004/05/19 06:58:35 rbruder Exp $
 ! Description: openMDX Enterprise JavaBean Configuration DTD 1.0
 ! Revision:    $Revision: 1.12 $
 ! Owner:       OMEX AG, Switzerland, http://www.omex.ch
 ! Date:        $Date: 2004/05/19 06:58:35 $
 ! ====================================================================
 !
 ! This software is published under the BSD license
 ! as listed below.
 ! 
 ! Copyright (c) 2004, OMEX AG, Switzerland
 ! All rights reserved.
 ! 
 ! Redistribution and use in source and binary forms, with or
 ! without modification, are permitted provided that the following
 ! conditions are met:
 ! 
 ! * Redistributions of source code must retain the above copyright
 !   notice, this list of conditions and the following disclaimer.
 ! 
 ! * Redistributions in binary form must reproduce the above copyright
 !   notice, this list of conditions and the following disclaimer in
 !   the documentation and/or other materials provided with the
 !   distribution.
 ! 
 ! * Neither the name of the openMDX team nor the names of its
 !   contributors may be used to endorse or promote products derived
 !   from this software without specific prior written permission.
 ! 
 ! THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 ! CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 ! INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 ! MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 ! DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 ! BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 ! EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 ! TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 ! DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 ! ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 ! OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 ! OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 ! POSSIBILITY OF SUCH DAMAGE.
 ! 
 ! _________________
 ! 
 ! This product includes software developed by the Apache Software
 ! Foundation (http://www.apache.org/).
 !-->
<!--
XML DTD for openMDX specific Enterprise JavaBeans Extension deployment
descriptor. This DTD is intended to be accompanied with a Java 2
Enterprise JavaBean 2.0 deployment descriptor (ejb-jar.xml).

All openMDX Enterprise JavaBeans Extension 1.0 deployment descriptors 
must include a DOCTYPE of the following form:

  <!DOCTYPE openmdx-ejb-jar PUBLIC
	"-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN"
	"http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
-->
<!--
  *********************************************************************
  openMDX Enterprise JavaBean Configuration
  *********************************************************************
-->
<!--
The openmdx-ejb-jar element is the root element of the openMDX EJB deployment
descriptor. 

It contains
	- an optional description of the openmdx-ejb-jar file
	- mandatory container for EJB configuration extensions
	
Example:

        <openmdx-ejb-jar>
        	<enterprise-beans>
        		<session>
        			<ejb-name>Roger</ejb-name>
        			<ejb-ref>
        				<ejb-ref-name>ejb/Daniel</ejb-ref-name>
        				<jndi-name>org/openmdx/test/Daniel</jndi-name>
        			</ejb-ref>
        			<ejb-local-ref>
        				<ejb-ref-name>ejb/Markus</ejb-ref-name>
        				<local-jndi-name>org/openmdx/test/Markus</local-jndi-name>
        			</ejb-local-ref>
        			<pool>
        				<initial-capacity>1</initial-capacity>
        				<maximum-capacity>100</maximum-capacity>
        				<timeout>1000000</timeout>
        			</pool>
        		</session>
        		<session>
        			<ejb-name>Martin</ejb-name>
        			<jndi-name>org/openmdx/test/Martin</jndi-name>
        			<home-class>TestHomeClass</home-class>
        			<local-home-class>TestLocalHomeClass</local-home-class>
        		</session>
        		<session>
        			<ejb-name>Juerg</ejb-name>
        			<local-jndi-name>org/openmdx/test/Juerg</local-jndi-name>
        		</session>
        	</enterprise-beans>
        </openmdx-ejb-jar>	
		
-->
<!ELEMENT openmdx-ejb-jar (description?, enterprise-beans)>
<!--
The description element is used to provide text describing the parent element.

This is an optional element.
-->
<!ELEMENT description (#PCDATA)>
<!--
The enterprise-beans element contains the declarations of one or more
enterprise beans.

Used in: openmdx-ejb-jar
-->
<!ELEMENT enterprise-beans (session*, message-driven*)>
<!--
The session element declares a session bean. The declaration consists
of:
	- an optional description
	- a name assigned to the enterprise bean in the deployment description
	- the specification of the session bean's remote home, if any
	- the specification of the session bean's local home, if any
	- an optional declaration of the bean's references.
	- an optional configuration of the session bean's pool

The elements that are optional are "optional" in the sense that they
are omitted when if lists represented by them are empty.

Either both the local-home and the local elements or both the
home and the remote elements must be specified for the session bean.

Used in: enterprise-beans
-->
<!ELEMENT session (description?, ejb-name, jndi-name?, local-jndi-name?, home-class?, local-home-class?, ejb-ref*, ejb-local-ref*, resource-ref*, resource-env-ref*, pool?)>
<!--
The message-driven element declares a message driven bean. The declaration consists
of:
	- an optional description
	- a name assigned to the enterprise bean in the deployment description
	- an optional declaration of the bean's references.
	- an optional configuration of the message driven bean's pool

The elements that are optional are "optional" in the sense that they
are omitted when if lists represented by them are empty.

Used in: enterprise-beans
-->
<!ELEMENT message-driven (description?, ejb-name, jndi-name?, local-jndi-name?, ejb-ref*, ejb-local-ref*, resource-ref*, resource-env-ref*, pool?)>
<!--
The ejb-name element specifies an enterprise bean's name. This name is
assigned by the ejb-jar file producer to name the enterprise bean in
the ejb-jar file's deployment descriptor. The name must be unique
among the names of the enterprise beans in the same ejb-jar file. The
enterprise bean code does not depend on the name; therefore the name
can be changed during the application-assembly process without
breaking the enterprise bean's function. There is no architected
relationship between the ejb-name in the deployment descriptor and the
JNDI name that the Deployer will assign to the enterprise bean's home.
The name must conform to the lexical rules for an NMTOKEN.

Used in: session

Example:
<ejb-name>PetStore</ejb-name>
-->
<!ELEMENT ejb-name (#PCDATA)>
<!--
The optional home-class element contains the ejb's remote home implementation class.

The home-class element is optional for some predefined combinations of 
home end ejb classes, e.g.
  
	<home> is org.openmdx.compatibility.application.dataprovider.transport.ejb.cci.Dataprovider_1Home
	<home-class> defaults to org.openmdx.compatibility.application.dataprovider.transport.ejb.spi.Dataprovider_1HomeImpl
	<ejb-class> must be an instance of org.openmdx.compatibility.base.dataprovider.cci.Dataprovider_1_0

Used in: session
-->
<!ELEMENT home-class (#PCDATA)>
<!--
The optional local-home-class element contains the ejb's local home implementation class.

The local-home-class element is optional for some predefined combinations of 
local-home end ejb classes, e.g.
  
	<local-home> is org.openmdx.compatibility.application.dataprovider.transport.ejb.cci.Dataprovider_1LocalHome
	<local-home-class> defaults to org.openmdx.compatibility.application.dataprovider.transport.ejb.spi.Dataprovider_1LocalHomeImpl
	<ejb-class> must be an instance of org.openmdx.compatibility.base.dataprovider.cci.Dataprovider_1_0

Used in: session
-->
<!ELEMENT local-home-class (#PCDATA)>
<!--
  *********************************************************************
  openMDX JNDI Mapping
  *********************************************************************
-->
<!-- 
This specifies a JNDI name to reference a bean
Used in: session, ejb-ref, resource-ref, resource-env-ref
-->
<!ELEMENT jndi-name (#PCDATA)>
<!-- 
This specifies a JNDI name to reference a local bean
Used in: session, ejb-local-ref
-->
<!ELEMENT local-jndi-name (#PCDATA)>
<!--
The ejb-ref-name element specifies the name of an environment 
reference. Its value is the reference name used in the enterprise 
bean's deployment descriptor.
Used in: ejb-ref, ejb-local-ref

Examples: 
<ejb-ref-name>ejb/PetStore</ejb-ref-name>

-->
<!ELEMENT ejb-ref-name (#PCDATA)>
<!ELEMENT res-ref-name (#PCDATA)>
<!ELEMENT resource-env-ref-name (#PCDATA)>
<!--
The ejb-ref element is used to map the ejb-ref-name of an EJB reference
(provided in ejb-jar.xml) to a JNDI name.
Used in: session
-->
<!ELEMENT ejb-ref (ejb-ref-name, jndi-name)>
<!--
The ejb-local-ref element is used to map the ejb-ref-name of a local EJB 
reference (provided in ejb-jar.xml) to a JNDI name.
Used in: session
-->
<!ELEMENT ejb-local-ref (ejb-ref-name, local-jndi-name)>
<!--
The resource-ref element is used to map the res-ref-name of a resource 
reference (provided in ejb-jar.xml) to a JNDI name.
Used in: session
-->
<!ELEMENT resource-ref (res-ref-name, jndi-name)>
<!--
The resource-ref element is used to map the resource-env-ref-name of a resource 
env reference (provided in ejb-jar.xml) to a JNDI name.
Used in: session
-->
<!ELEMENT resource-env-ref (resource-env-ref-name, jndi-name)>

<!--
  *********************************************************************
  Pool Configuration
  *********************************************************************
-->
<!--
The pool element is the root element for providing 
specific parameters for this enterprise java bean pool.

openMDX will use these specifications in controlling the behavior of the
maintained pool of enterprise java beans.

This is an optional element.  Failure to specify this element or any of its
specific element items will result in default values being assigned.  Refer to
the description of each individual element for the designated default value.

Used in: session
-->
<!ELEMENT pool (initial-capacity?, maximum-capacity?, maximum-wait?)>
<!--
The initial-capacity element identifies the initial number of bean instances
which the openMDX Container will attempt to obtain during deployment.

This is an optional element.

Failure to specify this value will result in openMDX using its defined default value.

Default Value:	1

Used in: pool 
-->
<!ELEMENT initial-capacity (#PCDATA)>
<!--
The maximum-capacity element identifies the maximum number of bean instances
which the openMDX Container will allow.  Requests beyond this limit will result in
blocking the caller until an isntance is available or returning an exception if
maximum-time is reached.

This is an optional element.

Failure to specify this value will result in openMDX using its defined default value.

Default Value:  java.lang.Integer.MAX_VALUE

Used in: pool 
-->
<!ELEMENT maximum-capacity (#PCDATA)>
<!--
The maximum-wait element identifies the time in milliseconds to wait for an 
instance to be returned to the pool when there are maximum-capacity active instances.

A value of 0 will mean not to wait at all. When a request times out 
waiting for an instance an Exception is generated and the call aborted.

This is an optional element.

Failure to specify this value will result in openMDX using its defined default value.

Default Value:	java.lang.Long.MAX_VALUE

Used in: pool 
-->
<!ELEMENT maximum-wait (#PCDATA)>

=== DlRTY-HARRY/openmdx/test-core/src/ear/test-transaction.ear/gateway1.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
  	<enterprise-beans>
    	<session>
      		<ejb-name>ejb20Entities</ejb-name>
			<local-jndi-name>test/openmdx/ejb20/EntityManagerFactory</local-jndi-name>
	      	<pool>
	        	<initial-capacity>1</initial-capacity>
	        	<maximum-capacity>10</maximum-capacity>
	        	<maximum-wait>10000</maximum-wait>
	      	</pool>
    	</session>
  	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-core/etc/org.openmdx.test.base.application.deploy/test1.ear.fully-exploded/two.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
	<enterprise-beans>
		<session>
			<ejb-name>Martin</ejb-name>
			<jndi-name>org/openmdx/test/Martin</jndi-name>
			<home-class>TestHomeClass</home-class>
			<local-home-class>TestLocalHomeClass</local-home-class>
		</session>
		<session>
			<ejb-name>Juerg</ejb-name>
			<local-jndi-name>org/openmdx/test/Juerg</local-jndi-name>
		</session>
		<message-driven>
			<ejb-name>Andy</ejb-name>
			<jndi-name>org/openmdx/test/Andy</jndi-name>
			<local-jndi-name>org/openmdx/local/test/Andy</local-jndi-name>
		</message-driven>
	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-core/src/ear/test-pki.ear/test-pki.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Harald Burger (private) -->
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
	<enterprise-beans>
		<session>
			<ejb-name>pki-preferences1</ejb-name>
			<jndi-name>org/openmdx/test/resource/security/pki/preferences1</jndi-name>
			<resource-ref>
				<res-ref-name>pki/key</res-ref-name>
				<jndi-name>pki/KeyProvider</jndi-name>
			</resource-ref>
			<resource-ref>
				<res-ref-name>pki/certificate</res-ref-name>
				<jndi-name>pki/CertificateProvider</jndi-name>
			</resource-ref>
		</session>
	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/document/src/ear/junit-test.ear/document1.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
  	<enterprise-beans>
    	<session>
      		<ejb-name>document1-Volatile</ejb-name>
			<jndi-name>org/openmdx/test/document1/Volatile</jndi-name>
	      	<pool>
	        	<initial-capacity>1</initial-capacity>
	        	<maximum-capacity>10</maximum-capacity>
	        	<maximum-wait>10000</maximum-wait>
	      	</pool>
    	</session>
    	<session>
      		<ejb-name>document1-Persistent</ejb-name>
			<jndi-name>org/openmdx/test/document1/Persistent</jndi-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/openMDX_test</jndi-name>
			</resource-ref>
	      	<pool>
	        	<initial-capacity>1</initial-capacity>
	        	<maximum-capacity>10</maximum-capacity>
	        	<maximum-wait>10000</maximum-wait>
	      	</pool>
    	</session>
  	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-core/src/ear/test-state.ear/entity-provider.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
  	<enterprise-beans>
    	<session>
      		<ejb-name>EntityManagerFactory</ejb-name>
			<local-jndi-name>test/openmdx/state2/EntityProviderFactory</local-jndi-name>
	      	<pool>
	        	<initial-capacity>1</initial-capacity>
	        	<maximum-capacity>10</maximum-capacity>
	        	<maximum-wait>10000</maximum-wait>
	      	</pool>
    	</session>
    	<session>
      		<ejb-name>Gateway</ejb-name>
			<jndi-name>test/openmdx/state2/Gateway</jndi-name>
	      	<pool>
	        	<initial-capacity>1</initial-capacity>
	        	<maximum-capacity>10</maximum-capacity>
	        	<maximum-wait>10000</maximum-wait>
	      	</pool>
    	</session>
  	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-core/src/ear/test-extension.ear/provider1.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
	<enterprise-beans>
		<session>
			<ejb-name>Default</ejb-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/dataproviders</jndi-name>
			</resource-ref>
		</session>
		<session>
			<ejb-name>Numeric</ejb-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/dataproviders</jndi-name>
			</resource-ref>
		</session>
		<session>
			<ejb-name>Native</ejb-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/dataproviders</jndi-name>
			</resource-ref>
		</session>
	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-core/src/ear/test-persistence.ear/test-jdbc-1.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Harald Burger (private) -->
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
	<enterprise-beans>
		<session>
			<ejb-name>generic</ejb-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/dataproviders</jndi-name>
			</resource-ref>
		</session>
		<session>
			<ejb-name>sliced</ejb-name>
			<resource-ref>
				<res-ref-name>jdbc/datasource[0]</res-ref-name>
				<jndi-name>jdbc/dataproviders</jndi-name>
			</resource-ref>
		</session>
		<session>
			<ejb-name>explorer</ejb-name>
			<jndi-name>org/openmdx/test/joining/explorer</jndi-name>
		</session>
	</enterprise-beans>
</openmdx-ejb-jar>

=== DlRTY-HARRY/openmdx/test-ejb/src/ear/test1.ear.fully-exploded/one.jar/META-INF/openmdx-ejb-jar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE openmdx-ejb-jar PUBLIC "-//openMDX//DTD Enterprise JavaBeans Extension 1.0//EN" "http://www.openmdx.org/dtd/openmdx-ejb-jar_1_0.dtd">
<openmdx-ejb-jar>
  <enterprise-beans>
    <session>
      <ejb-name>Roger</ejb-name>
      <ejb-ref>
        <ejb-ref-name>ejb/Daniel</ejb-ref-name>
        <jndi-name>org/openmdx/test/Daniel</jndi-name>
      </ejb-ref>
      <ejb-local-ref>
        <ejb-ref-name>ejb/Markus</ejb-ref-name>
        <local-jndi-name>org/openmdx/test/Markus</local-jndi-name>
      </ejb-local-ref>
      <resource-ref>
        <res-ref-name>resource/TestResourceRef</res-ref-name>
        <jndi-name>org/openmdx/test/resource/TestResourceRef</jndi-name>
      </resource-ref>
      <resource-env-ref>
        <resource-env-ref-name>resource-env/TestResourceEnvRef</resource-env-ref-name>
        <jndi-name>org/openmdx/test/resource-env/TestResourceEnvRef</jndi-name>
      </resource-env-ref>
      <pool>
        <initial-capacity>1</initial-capacity>
        <maximum-capacity>100</maximum-capacity>
        <maximum-wait>1000000</maximum-wait>
      </pool>
    </session>
  </enterprise-beans>
</openmdx-ejb-jar>
